insert into public.attractions (name, slug, description, category, municipality, region, latitude, longitude, trail_level, guide_required, images, featured)
values
  ('Pedra do Altar', 'pedra-do-altar', 'Formação rochosa imponente no litoral sul da Paraíba, a Pedra do Altar é um dos pontos mais fotografados da região. O acesso é feito por uma trilha de dificuldade moderada e o visual do topo compensa todo o esforço.', 'natural_formation', 'Conde', 'Litoral Sul', -7.2681, -34.9042, 'moderate', 'recommended', array['/placeholder.svg'], true),
  ('Praia de Tambaba', 'praia-de-tambaba', 'Uma das praias mais famosas da Paraíba, conhecida por suas águas claras, falésias coloridas e por ser a primeira praia de naturismo do Nordeste. Também possui áreas de uso comum para todos os visitantes.', 'beach', 'Conde', 'Litoral Sul', -7.2414, -34.9156, 'none', 'not_required', array['/placeholder.svg'], true),
  ('Centro Histórico de João Pessoa', 'centro-historico-joao-pessoa', 'O centro histórico mais oriental das Américas reúne casarões coloniais, igrejas centenárias, museus e a famosa Pedra do Rosário. Ideal para quem quer conhecer a história e a cultura da Paraíba.', 'heritage', 'João Pessoa', 'Litoral', -7.1150, -34.8641, 'none', 'not_required', array['/placeholder.svg'], true),
  ('Estação Ciência, Cultura e Artes', 'estacao-ciencia-cultura-artes', 'Espaço cultural em João Pessoa com exposições interativas de ciência, planetário, teatro e áreas de convivência. Ótimo para famílias e crianças.', 'culture', 'João Pessoa', 'Litoral', -7.1047, -34.8450, 'none', 'not_required', array['/placeholder.svg'], false),
  ('Pico do Jabre', 'pico-do-jabre', 'O ponto mais alto da Paraíba, localizado na Serra do Teixeira. Com mais de 1.100 metros de altitude, oferece trilhas desafiadoras e uma vista panorâmica da região do Cariri paraibano.', 'trail', 'Maturéia', 'Serra', -7.2833, -37.3500, 'difficult', 'recommended', array['/placeholder.svg'], true),
  ('Fenda da Baba', 'fenda-da-baba', 'Monumento natural formado por enormes blocos de granito que criam uma fenda impressionante. Local de importância histórica e paisagística no sertão paraibano.', 'natural_formation', 'Santa Luzia', 'Sertão', -7.1000, -36.9000, 'easy', 'not_required', array['/placeholder.svg'], false),
  ('Serra do Bodopitá', 'serra-do-bodopita', 'Área de preservação com paisagens de serra, clima ameno e trilhas leves. Um dos destinos de natureza mais agradáveis do Agreste paraibano.', 'nature', 'Fagundes', 'Agreste', -7.3500, -35.7833, 'easy', 'not_required', array['/placeholder.svg'], false),
  ('Cachoeira do Inferno', 'cachoeira-do-inferno', 'Queda d''água cercada pela vegetação da Mata Atlântica, acessível por trilha de nível moderado. Ótima parada para banho e contato com a natureza no Brejo paraibano.', 'nature', 'Areia', 'Brejo', -7.1200, -35.7000, 'moderate', 'recommended', array['/placeholder.svg'], false);
